### ISSUE TITLE
Several questions regarding data input

### ISSUE THREAD

**Issue by tkchafin** [pomo-dev/PoMo#3]
I came across the new Systematic Biology manuscript on BioRxiv and have been trying to get it PoMo to work for a while now... I have it working on the example datasets, and am now trying to apply it to my own.

I am currently working on using the scripts provided with PoMo to convert a fasta file of concatenated sequences to the .cf format, and have a few questions:

1) Is there some way of handling missing data or gaps? I can otherwise filter out all columns in the data matrix containing N's or gaps, but with reduced-representation genomic methods we usually have a lot of missing data, and so this won't leave much. 

2) Is there a way to represent heterozygotes? I have them coded using IUPAC codes, but cf.py seems to choke because it isn't [ACGT] 

3) The readme says that a workaround is required for datasets only including SNPs? 

Thank you

**Comment by dschrempf** [comment]
Hello,

thank you very much for your interest in PoMo.

I guess that you are converting Fasta files with `FastaToCounts.py`.  If
so, I pushed a fix to the GitHub repository that allows you to convert
sequences using IUPAC codes with this script.  If, e.g., an 'R' is
encountered in a population, an A and a G are counted.  If an 'N' or a
gap is encountered, no base counts are added at this site for this
specific population.

However, especially if heterozygotes are encoded with IUPAC codes, the
analysis might be biased because polymorphisms are counted twice.  Fixed
bases also would need to be counted twice then.  Do you think this is
necessary with your kind of data?

Furthermore, handling of 'N's and gaps is the same (no counts are added)
at the moment.  I am not sure if this behavior is wanted.

Ad 3.  At the moment, we run PoMo only on data sets that include
non-variable sites.  The reason is that upon maximization of the
likelihood, PoMo estimates the number of polymorphisms in the data.  If
this estimate is wrong (and it will be wrong if only polymorphic sites
are considered), PoMo might not be able to infer meaningful trees and
parameters.  You may want to try to run PoMo on variable data only, but
we do not advice you to do it.  I will ask the previous developer of
PoMo if he had any ideas in mind when he added this sentence to the
README.

Thanks again for your interest and I hope that I could help you!

Best wishes,
Dominik Schrempf

**Comment by tkchafin** [comment]
"Fixed bases also would need to be counted twice then.  Do you think this is
necessary with your kind of data?"

I think this would be my preferred option, having both alleles counted in all cases (assuming diploidy). I could alternatively just split each individual onto two lines, with the heterozygous sites then could be represented as the respective AGTC alleles. My only concern is that now this would double the number of counted alleles, and since the population size cap is 10, so I would be more likely to lose alleles? Could I just change the hardcoded "N = 10" value in PoMo.py, or would that conflict with hardcoded values elsewhere? 

"Furthermore, handling of 'N's and gaps is the same (no counts are added) at the moment.  I am not sure if this behavior is wanted." 

This would be preferred as well. 

"At the moment, we run PoMo only on data sets that include non-variable sites. "

I have full sequences, I just wanted to try only variable sites to speed up analyses. From what it says in the manuscript, this should still be pretty fast even with the full dataset. I have been trying to use SNAPP, but so far it has taken 30 days just to run 400,000 generations on a 32-core machine. 

Thank you for your help!

**Comment by tkchafin** [comment]
I have the attached input file, and PoMo seems to be choking on it, giving the following output:

PoMo 1.1.0
 Created by Nicola De Maio; maintained by Dominik Schrempf. For a
reference, please see and cite: De Maio, Schlotterer, Kosiol (MBE,
2013), and/or: De Maio, Schrempf, Kosiol (in preparation). You can use
this software for non-commercial purposes, but please, always
acknowledge the authors. For suggestions, doubts, bugs, etc., please
contact nicola.de.maio.85@gmail.com
===========================================================
Start Time: 2016-01-15 02:45:54
Verbose mode.
===========================================================
Starting to read input file.
Traceback (most recent call last):
  File "/home/mrd1/acamel/local/bin/PoMo.py", line 201, in <module>
    theta, vb)
  File "/home/mrd1/acamel/local/src/PoMo/libPoMo/main.py", line 309, in read_data_write_HyPhy_input
    cfStr = lp.cf.CFStream(fn)
  File "/home/mrd1/acamel/local/src/PoMo/libPoMo/cf.py", line 213, in __init__
    (chrom, pos, countsL) = interpret_cf_line(ln)
  File "/home/mrd1/acamel/local/src/PoMo/libPoMo/cf.py", line 151, in interpret_cf_line
    countsL[i] = [int(el) for el in countsLStr[i]]
  File "/home/mrd1/acamel/local/src/PoMo/libPoMo/cf.py", line 151, in <listcomp>
    countsL[i] = [int(el) for el in countsLStr[i]]
ValueError: invalid literal for int() with base 10: '\n'

Any idea what is going wrong? It looks like somehow my line breaks are causing an error- I am guessing somewhere I have a formatting issue? 

Thanks 
[pomo.zip](https://github.com/pomo-dev/PoMo/files/91300/pomo.zip)

**Comment by dschrempf** [comment]
Hello,

this file runs fine on my computer:

    python PoMo.py HYPHYMP test.cf

Which command line and operating system are you using?

I will answer your previous comment shortly.

Best

**Comment by tkchafin** [comment]
I am using a bash shell on CentOS Linux. It is the setup on our cluster and so I don't really have much flexibility on that.

**Comment by dschrempf** [comment]
Hello,

the line is stripped of whitespace before analysis now, I hope this
helps.

Best.

**Comment by tkchafin** [comment]
Seems to be all working now! Thanks- will let you know how it turns out, or if I have any more issues
