### ISSUE TITLE
Cannot build Hyphy on a Mac OSX

### ISSUE THREAD

**Issue by bouzidnm** [pomo-dev/PoMo#5]
I've been trying to compile Hyphy using the provided instructions to install PoMo. 
`cmake ./` fails with the error:

"Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
...
Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS)"

I've installed a bunch of new OpenMP compatible compilers, including gcc, clang-omp, hoping it would solve the problem. It did not. All other dependencies are installed. When I try to proceed and run 
`make MP2` It fails with the following errors:

"make[3]: *** [CMakeFiles/HYPHYMP.dir/src/core/_hyExecutionContext.cpp.o] Error 1
make[2]: *** [CMakeFiles/HYPHYMP.dir/all] Error 2
make[1]: *** [CMakeFiles/MP2.dir/rule] Error 2
make: *** [MP2] Error 2"

Not sure if this is a problem with the Mac OSX or with the Makefile.

**Comment by dschrempf** [comment]
Hello,

thank you for your interest in PoMo.  I am sorry, but I cannot help you
with issues about compiling HyPhy on a Mac.  Maybe @Nicola De Maio can
help you with this.

If you do not succeed in compiling HyPhy, but you would like to use PoMo
on your data set, I urge you to try our new version.  It is reversible,
suitable for larger data sets and implemented into IQ-TREE because
IQ-TREE comes with tree search algorithms.

Please check out the code from
https://github.com/Cibiv/IQ-TREE/tree/PoMo

Instructions for compilation for all operating systems can be found at
http://www.cibiv.at/software/iqtree/doc/Compilation-Guide/

There is not much information about PoMo in the manual yet.  However,
you can check out PoMo-specific help with running `iqtree --help' (if
you compiled using the PoMo branch).

A command line example:
iqtree -s YourData.cf

I hope this helps,
Dominik

**Comment by NicolaDM** [comment]
Dear Dominik and bouzidnm,
This seems to be a problem of the old HyPhy versions with the new mac OS, see https://github.com/veg/hyphy/issues/192.
Might be worth checking if PoMo works with newer HyPhy versions.

Nicola

**Comment by NicolaDM** [comment]
Dear bouzidnm,
I will try to fix the issue with HyPhy.
In the meanwhile, if you don't have access to a linux machine or an older mac OS, there are 2 alternative implementations of PoMo that you can use: (i) the one on IQTree that Dominik mentioned, which is very fast; (ii) The very general (but slower) one on BEAST2 that you can find here https://bitbucket.org/nicofmay/pomo-beast/overview or that can you can install via BEAUti.

Best wishes,
Nicola
