### ISSUE TITLE
ModuleNotFoundError: No module named 'libPoMo'

### ISSUE THREAD

**Issue by jsan4christ** [pomo-dev/PoMo#6]
Hi,

Am trying to use this script but keep getting this error. 

I'm using centos7

$ scripts/FastaToVCF.py
Traceback (most recent call last):
  File "scripts/FastaToVCF.py", line 13, in <module>
    import libPoMo.fasta as fa  # noqa
ModuleNotFoundError: No module named 'libPoMo'

Please advise

**Comment by dschrempf** [comment]
Hello!

Thanks for your interest in PoMo! This repository was left for reference only. The updated and maintained conversion scripts can be found here:

https://github.com/pomo-dev/cflib

The up-to-date version of PoMo is now implemented in IQ-TREE 2:

http://www.iqtree.org/

Please let me know, if you need any other help! I will update the readme, so that it is clear where the new conversion scripts can be found!
